### ISSUE TITLE
Customising to throttle at user level

### ISSUE THREAD

**Issue by pathardepavan** [GrahamCampbell/Laravel-Throttle#48]
Hi ,
Is there any way I could throttle at a user level rather than at IP level ? Each api call has a unique key for user in every request. Can you please help me achieve this??

**Comment by GrahamCampbell** [comment]
Yes, just make your own middleware. Instead of passing the request through to https://github.com/GrahamCampbell/Laravel-Throttle/blob/master/src/Http/Middleware/ThrottleMiddleware.php#L58, pass an array: `['ip' => 'your user id', 'route' => $request->getPath()]`. You can see the transformer internals at https://github.com/GrahamCampbell/Laravel-Throttle/tree/master/src/Transformers.
