### ISSUE TITLE
[Question] Cache file size

### ISSUE THREAD

**Issue by Frondor** [GrahamCampbell/Laravel-Throttle#53]
I'm wondering if this package does (or can) take care of clearing cache (garbage collect) from old data (old throttles) automatically.

I mean, since the package uses cache to store throttle's data, even if it expires, the data is still in cache files (in case of using that driver), am I right?

In that case, I should also use something like a garbage collector, because doesn't sounds good to be manually clearing the cache once in a while because of this package data (I don't have any other use for cache actually in my app).
Please, correct me if I'm wrong.

**Comment by GrahamCampbell** [comment]
Yes, garbage collection is already taken of.

**Comment by Frondor** [comment]
Mind telling me in which part of this package is that logic? Because I couldn't find anything related to "forgetting" cache.
Having in mind that you aren't storing the generated keys (`sha1( ip + route )`) anywhere, how can those keys be forgotten if you have no records of them?

**Comment by GrahamCampbell** [comment]
Garbage collection is not handled by this package, and garbage collection will happen at any point after the cache entry has expired. Just because it's expired, or even been forgotten, it doesn't mean it's still not stored in the cache, it just means it's marked as expired.

For drivers like redis, redis itself will do the GC.
Laravel's file driver is not intended for production use, and does not come with garbage collection. It's only meant for local development.

**Comment by Frondor** [comment]
Then

> Yes, garbage collection is already taken of.

Is not a "kind" reply for the question, nor it answers the question correctly.
> Laravel's file driver is not intended for production use, and does not come with garbage collection. It's only meant for local development. 

Why isn't that in the docs? The docs don't say it is "_not intended for production use_", it only suggest to use a "more robust" solution for **larger apps**.

That being said, my question is now answered.
Thank you.

**Comment by GrahamCampbell** [comment]
Maybe it's worth you sending a PR to the laravel docs then, to point this out. :)
